/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package databases;

import ControlMulta.loginControlaMulta;
import acomodador.loginAcomodador;
import bibliotecario.loginBibLiotecario;
import jefe_biblioteca.loginJefeBiblioteca;
import subjefe_biblioteca.loginSubJefeBiblioteca;
import supervisorDeLaBD.loginSupervisorBD;
import vistasUsuariosNormales.loginUsuario;

/**
 *
 * @author Usersone
 */
public class vistaInicio extends javax.swing.JFrame {

    /**
     * Creates new form vistaInicio
     */
    DataBases b;

    public vistaInicio() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("INICIO");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usu_nurmal = new javax.swing.JButton();
        acomodador = new javax.swing.JButton();
        bibliotecario = new javax.swing.JButton();
        supervisor_abd = new javax.swing.JButton();
        supervisor_jefe = new javax.swing.JButton();
        controlador_multas = new javax.swing.JButton();
        supervisor_subjefe = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        usu_nurmal.setText("Usuario");
        usu_nurmal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usu_nurmalActionPerformed(evt);
            }
        });

        acomodador.setText("Acomodador");
        acomodador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acomodadorActionPerformed(evt);
            }
        });

        bibliotecario.setText("bibliotecario");
        bibliotecario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bibliotecarioActionPerformed(evt);
            }
        });

        supervisor_abd.setText("supervisor de la base de datos");
        supervisor_abd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supervisor_abdActionPerformed(evt);
            }
        });

        supervisor_jefe.setText("supervisor jefe de biblioteca");
        supervisor_jefe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supervisor_jefeActionPerformed(evt);
            }
        });

        controlador_multas.setText("controlador de multas");
        controlador_multas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                controlador_multasActionPerformed(evt);
            }
        });

        supervisor_subjefe.setText("supervisor sub jefe de biblioteca");
        supervisor_subjefe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supervisor_subjefeActionPerformed(evt);
            }
        });

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(supervisor_subjefe)
                    .addComponent(supervisor_jefe)
                    .addComponent(usu_nurmal)
                    .addComponent(supervisor_abd)
                    .addComponent(acomodador)
                    .addComponent(bibliotecario)
                    .addComponent(controlador_multas))
                .addGap(0, 176, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(usu_nurmal)
                .addGap(18, 18, 18)
                .addComponent(bibliotecario)
                .addGap(18, 18, 18)
                .addComponent(acomodador)
                .addGap(18, 18, 18)
                .addComponent(controlador_multas)
                .addGap(18, 18, 18)
                .addComponent(supervisor_jefe)
                .addGap(18, 18, 18)
                .addComponent(supervisor_abd)
                .addGap(18, 18, 18)
                .addComponent(supervisor_subjefe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usu_nurmalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usu_nurmalActionPerformed
        // TODO add your handling code here:
        loginUsuario usuario_normal = new loginUsuario();
        usuario_normal.setVisible(true);

    }//GEN-LAST:event_usu_nurmalActionPerformed

    private void supervisor_subjefeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supervisor_subjefeActionPerformed
        // TODO add your handling code here:
        loginSubJefeBiblioteca supervisor_subjefe = new loginSubJefeBiblioteca();
        supervisor_subjefe.setVisible(true);
    }//GEN-LAST:event_supervisor_subjefeActionPerformed

    private void supervisor_jefeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supervisor_jefeActionPerformed
        // TODO add your handling code here:  
        loginJefeBiblioteca supervisor_jefe = new loginJefeBiblioteca();
        supervisor_jefe.setVisible(true);
    }//GEN-LAST:event_supervisor_jefeActionPerformed

    private void controlador_multasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_controlador_multasActionPerformed
        // TODO add your handling code here:
        loginControlaMulta controla_multas = new loginControlaMulta();
        controla_multas.setVisible(true);
    }//GEN-LAST:event_controlador_multasActionPerformed

    private void supervisor_abdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supervisor_abdActionPerformed
        // TODO add your handling code here:
        loginSupervisorBD supervisor_abd = new loginSupervisorBD();
        supervisor_abd.setVisible(true);
    }//GEN-LAST:event_supervisor_abdActionPerformed

    private void acomodadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acomodadorActionPerformed
        // TODO add your handling code here:
        loginAcomodador acomodador = new loginAcomodador();
        acomodador.setVisible(true);
    }//GEN-LAST:event_acomodadorActionPerformed

    private void bibliotecarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bibliotecarioActionPerformed
        // TODO add your handling code here:
        loginBibLiotecario bibliotecario = new loginBibLiotecario();
        bibliotecario.setVisible(true);
    }//GEN-LAST:event_bibliotecarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton acomodador;
    public javax.swing.JButton bibliotecario;
    public javax.swing.JButton controlador_multas;
    private javax.swing.JButton jButton1;
    public javax.swing.JButton supervisor_abd;
    public javax.swing.JButton supervisor_jefe;
    public javax.swing.JButton supervisor_subjefe;
    private javax.swing.JButton usu_nurmal;
    // End of variables declaration//GEN-END:variables
}
